name: Build and Upload

on:
 push:
   branches: [master]

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Init submodules
     run: |
       git submodule init
       git submodule update --recursive --remote


   - name: Install Qt
     uses: jurplel/install-qt-action@v3
     with:
       version: '6.6.0'

   - name: Build
     run: |
       mkdir build
       cd build
       cmake .. -DCMAKE_BUILD_TYPE=Release
       cmake --build . --config Release
       cd Release
       windeployqt.exe "D:\a\SCCEX\SCCEX\build\Release\SugarContChatEditor.exe"
       copy ../include/jsoncpp/src/lib_json/Release/jsoncpp.dll .
       copy ../include/fmt/bin/Release/fmt.dll .
       copy ../../LICENSE .
       copy ../../static/* .

   - name: Archive production artifacts
     uses: actions/upload-artifact@v3.1.3
     with:
       name: SCCEX for Windows
       path: |
         ./build/Release/SugarContChatEditor.exe
         ./build/Release/Qt6Core.dll
         ./build/Release/Qt6Gui.dll
         ./build/Release/Qt6Widgets.dll
         ./build/Release/platforms/
         ./build/Release/styles/
         ./build/Release/jsoncpp.dll
         ./build/Release/fmt.dll
         ./build/Release/LICENSE
         ./build/Release/说明.txt
         ./build/Release/_vcruntime140_1.dll

   - name: Prepare full version
     run: |
       cd build/Release
       copy ../include/**/*.dll .
       
   - name: Upload full version
     uses: actions/upload-artifact@v3.1.3
     with:
       name: SCCEX for Windows (Full)
       path: |
         ./build/Release/*
