name: Build and Upload

on:
 push:
   branches: [master]

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Install Qt
     uses: jurplel/install-qt-action@v3
     with:
       version: '6.6.0'

   - name: Build
     run: |
       mkdir build
       cd build
       cmake .. -DCMAKE_BUILD_TYPE=Release
       cmake --build . --config Release
       cd Release
       windeployqt.exe "D:\a\SCCEX\SCCEX\build\Release\SugarContChatEditor.exe"

   - name: Archive production artifacts
     uses: actions/upload-artifact@v2
     with:
       name: SCCEX for Windows
       path: |
         ./build/Release/SugarContChatEditor.exe
         ./build/Release/Qt6Core.dll
         ./build/Release/Qt6Gui.dll
         ./build/Release/Qt6Widgets.dll
         ./build/Release/libEGL.dll
